# ---------------- LOCALHOST -------------------- #

### HTTP GET Request - Landing Page
GET http://localhost:3000 HTTP/1.1

### HTTP GET Request - Notes
GET http://localhost:3000/note HTTP/1.1

### HTTP GET Request - Notes
GET http://localhost:3000/note/640a1afb387774afa60eafaa HTTP/1.1

### HTTP POST request - Notes
POST http://localhost:3000/note HTTP/1.1
Content-Type: application/json

{
    "entryDate": "01-01-2023",
    "canon": "Book of Mormon",
    "book": "Alma",
    "chapter": 32,
    "verse": 21,
    "note": "Good verse"
}

### HTTP PUT request - Notes
PUT http://localhost:3000/note/640a1afb387774afa60eafaa HTTP/1.1
Content-Type: application/json

{
    "entryDate": "03-08-2023",
    "canon": "Book of Mormon",
    "book": "Alma",
    "chapter": 22,
    "verse": 11,
    "note": "Good verse"
}

### HTTP DELETE Request - Notes
DELETE http://localhost:3000/note/640a1afb387774afa60eafaa HTTP/1.1

### HTTP POST request - Journals
POST http://localhost:3000/journal HTTP/1.1
Content-Type: application/json

{
    "title": "Personal study about prayer",
    "description": "Prayer is a wonderful thing",
    "createDate": "01-01-2023"
}

### HTTP POST request - Topics
POST http://localhost:3000/topic HTTP/1.1
Content-Type: application/json

{
    "title": "Faith",
    "description": "Faith is like a seed"
}

### HTTP POST request - Users
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "githubId": "8313847365",
    "userName": "newUser1234",
    "email": "howdy@email.com"
}

# ---------------- PRODUCTION ------------------- #

### HTTPS GET Request - Landing Page
GET https://cse341-project.onrender.com HTTP/1.1